### ISSUE TITLE
Please share Sample code

### ISSUE THREAD

**Issue by vikingsvivek** [k3rn3l-p4n1c/postpython#1]
Please share a sample how can use this to call postman collections?

**Comment by k3rn3l-p4n1c** [comment]
Isn't `README.md` clear enough? Can you give me feedback to update it?

from postpython.core import PostPython
runner = PostPython('/path/to/collection/Postman echo.postman_collection')
response = runner.RequestMethods.get_request()
print(response.json())
print(response.status_code)

**Comment by bardia-heydari** [comment]
It seems that the readme.md file is not clear enough.
To call a postman request you should replace your name of the folder and the request. 
For example if your folder is named Translation and  request is named translate your code would be something like this:
runner.Translation.translate()

**Comment by intiamaru** [comment]
Hi k3rn3l-p4n1c it is still not very clear, I dont get the idea of creating an additional folder, is there a way to share a piece of sample code in the repo, maybe I can contact you?
