### ISSUE TITLE
Unable to parse the collection's requests field

### ISSUE THREAD

**Issue by ddevassy** [k3rn3l-p4n1c/postpython#4]
Getting error while executing 

> I/P File - test.py
> pp = PostPython('/Users/dasfdy/Desktop/test/Rn CRUD.postman_collection.json')
> pp.environments.update({'BASE_URL': 'http://127.0.0.1:5000', 'PASSWORD': 'test', 'EMAIL': 'info@example.com'})
> pp.environments.update(pp.User.login().json()['message'])
> 
> print(pp.User.get_my_info().json())
> 
> 
> O/P Snippet

> Traceback (most recent call last):
>   File "/Users/dasfdy/Documents/learn_python/postman_test/1.py", line 3, in <module>
>     runner = PostPython('/Users/ddevassy/Desktop/test/Rn CRUD.postman_collection.json')
>   File "/Users/dasfdy/Documents/learn_python/postpython/postpython/core.py", line 31, in __init__
>     self.__load()
>   File "/Users/dasfdy/Documents/learn_python/postpython/postpython/core.py", line 35, in __load
>     for req in self.__postman_collection['requests']:
> KeyError: 'requests'

**Comment by bardia-heydari** [comment]
You have to export the collection from Postman as a "Collection v1(deprecated)" otherwise this package cannot read it. It will be fixed soon.

**Comment by bardia-heydari** [comment]
The discussion will be continued in #6
