### ISSUE TITLE
Getting KeyError

### ISSUE THREAD

**Issue by satish-chowdhary** [k3rn3l-p4n1c/postpython#5]
File ".\api_test.py", line 10, in <module>
    runner = PostPython('E://Project//flask_api_test//sample_api_test.postman_collection.json')
  File "E:\Project\open\lib\site-packages\postpython\core.py", line 31, in __init__
    self.__load()
  File "E:\Project\open\lib\site-packages\postpython\core.py", line 35, in __load
    for req in self.__postman_collection['requests']:
KeyError: 'requests'

**Comment by martindunford** [comment]
You have to export the collection from Postman as a "Collection v1(deprecated)" otherwise this package cannot read it. Basically it is not up to date with Postman

**Comment by k3rn3l-p4n1c** [comment]
Duplicate of #6 
will be fixed soon

**Comment by bardia-heydari** [comment]
Duplicate of #6
will be fixed soon
